from ChessVar import ChessVar

board = ChessVar()
print('Getting player turn (black or white):', board.get_turn())
# print(board.set_turn())
print('Getting game state (if a player won and if so, who):', board.get_game_state())
# print(board.get_turn())
print('Initial board state:')
board.print_board()
# # # print('Get Piece on Board:', board.get_piece('C8'))
# #
# # # My TEST for Playing the Game:
# # print('My Test for Playing the Game')
# # print('---------------------------------------')
print(board.make_move('a2', 'a4'))
print(board.make_move('a7', 'a6'))
board.print_board()
print(board.make_move('g1', 'f3'))
print(board.make_move('a6', 'a5'))
board.print_board()
print(board.get_turn())
print(board.make_move('c2', 'c3'))
print(board.make_move('a8', 'a6'))
print(board.make_move('c1', 'c4'))
print(board.make_move('d2', 'd4'))
print(board.get_turn())
board.print_board()
print(board.make_move('a6', 'e2'))
print(board.get_turn())
print(board.make_move('e7', 'e6'))
board.print_board()
print(board.make_move('f3', 'e5'))
board.print_board()
print(board.make_move('a6', 'd6'))
print(board.make_move('e5', 'd7'))
board.print_board()
print(board.get_game_state())
print(board.make_move('e6', 'e5'))
print(board.get_game_state())
print(board.get_turn())
board.print_board()
# #
# # # Reset the game and play again:
# # board.reset_game()
# # print(board.get_game_state())
# # print(board.get_turn())
#
# # # Knight test all movements:
# # board.reset_knight_test()
# # print(board.get_game_state())
# # print(board.get_turn())
# # board.print_board()
# # board.set_turn()
# # print(board.make_move('e4', 'f2'))
# # print(board.get_game_state())
# # board.print_board()
# # print(board.get_turn())
# # board.reset_knight_test()
# # board.set_turn()
# # print(board.make_move('e4', 'g3'))
# # board.print_board()
# # board.reset_knight_test()
# # board.set_turn()
# # print(board.make_move('e4', 'g5'))
# # board.print_board()
# # board.reset_knight_test()
# # board.set_turn()
# # print(board.make_move('e4', 'f6'))
# # board.print_board()
# # board.reset_knight_test()
# # board.set_turn()
# # print(board.make_move('e4', 'd6'))
# # board.print_board()
# # board.reset_knight_test()
# # board.set_turn()
# # print(board.make_move('e4', 'c5'))
# # board.print_board()
# # board.reset_knight_test()
# # board.set_turn()
# # print(board.make_move('e4', 'c3'))
# # board.print_board()
# # board.reset_knight_test()
# # board.set_turn()
# # print(board.make_move('e4', 'd2'))
# # board.print_board()
#
# # # Pawn Test all Movements:
# # board.print_board()
# # board.reset_game()
# # print(board.make_move('e2', 'e3'))
# # print(board.make_move('f7', 'f5'))
# # board.print_board()
# # print(board.make_move('e3', 'e2'))
# # print(board.make_move('c3', 'f5'))
# # print(board.make_move('f2', 'f4'))
# # board.print_board()
# # print(board.make_move('f5', 'f4'))
# # print(board.make_move('f5', 'e4'))
# # print(board.make_move('b7', 'b6'))
# # board.print_board()
# # print(board.make_move('e3', 'e5'))
# # print(board.make_move('e3', 'e4'))
# # board.print_board()
# # print(board.make_move('f5', 'e4'))
# # board.print_board()
#
# # # Rook Test All Movements:
# # board.reset_rook_test()
# # print(board.get_game_state())
# # print(board.get_turn())
# # board.print_board()
# # board.set_turn()
# # print(board.make_move('d5', 'd6'))
# # board.print_board()
# # board.reset_rook_test()
# # board.set_turn()
# # print(board.make_move('d5', 'c5'))
# # board.print_board()
# # board.reset_rook_test()
# # board.set_turn()
# # print(board.make_move('d5', 'b5'))
# # board.print_board()
# # board.reset_rook_test()
# # board.set_turn()
# # print(board.make_move('d5', 'a5'))
# # board.print_board()
# # board.reset_rook_test()
# # board.set_turn()
# # print(board.make_move('d5', 'z5')) #False
# # board.print_board()
# # board.reset_rook_test()
# # board.set_turn()
# # print(board.make_move('d5', 'd4'))
# # board.print_board()
# # board.reset_rook_test()
# # board.set_turn()
# # print(board.make_move('d5', 'd3'))
# # board.print_board()
# # board.reset_rook_test()
# # board.set_turn()
# # print(board.make_move('d5', 'd2'))
# # board.print_board()
# # print(board.get_game_state())  # Black Wins
# # board.reset_rook_test()
# # board.set_turn()
# # print('HERE')
# # board.print_board()
# # print(board.make_move('d5', 'd1'))  # False, cannot move through another piece
# # board.print_board()
# # board.reset_rook_test()
# # board.set_turn()
# # print(board.make_move('d5', 'e5'))
# # board.print_board()
# # board.reset_rook_test()
# # board.set_turn()
# # print(board.make_move('d5', 'g5'))
# # board.print_board()
# # board.reset_rook_test()
# # board.set_turn()
# # print(board.make_move('d5', 'h5'))
# # board.print_board()
# # board.reset_rook_test()
# # board.set_turn()
# # print(board.make_move('d5', 'j5'))  # False
# # board.print_board()
# # board.reset_rook_test()
# # board.set_turn()
# # print(board.make_move('d5', 'i5'))  # False
# # board.print_board()
# # board.reset_rook_test()
# # board.set_turn()
# # print(board.make_move('d5', 'c4'))  # False, cannot move like the bishop
# # board.print_board()
# # board.reset_rook_test()
# # board.set_turn()
# # print(board.make_move('d5', 'f4'))  # False, cannot move like the knight
# # board.print_board()
#
# # # Bishop Test All Movements:
# # board.reset_bishop_test()
# # board.set_turn()
# # board.print_board()
# # print(board.make_move('d5', 'e6'))
# # board.print_board()
# # board.reset_bishop_test()
# # board.set_turn()
# # print(board.make_move('d5', 'f7'))  # False
# # board.print_board()
# # board.reset_bishop_test()
# # board.set_turn()
# # print(board.make_move('d5', 'e4'))
# # board.print_board()
# # board.reset_bishop_test()
# # board.set_turn()
# # print(board.make_move('d5', 'f3'))
# # board.print_board()
# # board.reset_bishop_test()
# # board.set_turn()
# # print(board.make_move('d5', 'g2'))
# # board.print_board()
# # board.reset_bishop_test()
# # board.set_turn()
# # print(board.make_move('d5', 'h2'))  # False, cannot go through other pieces
# # board.print_board()
# # board.reset_bishop_test()
# # board.set_turn()
# # print(board.make_move('d5', 'c4'))
# # board.print_board()
# # board.reset_bishop_test()
# # board.set_turn()
# # print(board.make_move('d5', 'b3'))
# # board.print_board()
# # board.reset_bishop_test()
# # board.set_turn()
# # print(board.make_move('d5', 'a2'))
# # board.print_board()
# # board.reset_bishop_test()
# # board.set_turn()
# # print(board.make_move('d5', 'd2'))  # False, cannot move like the rook
# # board.print_board()
# # board.reset_bishop_test()
# # board.set_turn()
# # print(board.make_move('d5', 'f4'))  # False, cannot move like the knight
# # board.print_board()
#
# # # Queen Test All Movements:
# # board.reset_queen_test()
# # board.set_turn()
# # board.print_board()
# # print(board.make_move('d5', 'e6'))
# # board.print_board()
# # board.reset_queen_test()
# # board.set_turn()
# # print(board.make_move('d5', 'f7'))  # False
# # board.print_board()
# # board.print_board()
# # board.reset_queen_test()
# # board.set_turn()
# # print(board.make_move('d5', 'd3'))
# # board.print_board()
# # board.reset_queen_test()
# # board.set_turn()
# # print(board.make_move('d5', 'd2'))
# # board.print_board()
# # board.reset_queen_test()
# # board.set_turn()
# # print(board.make_move('d5', 'f4'))  # False, cannot move like the knight
# # board.print_board()
#
# # # King Test All Movements:
# # board.reset_king_test()
# # board.set_turn()
# # board.print_board()
# # print(board.make_move('d5', 'e6'))
# # board.print_board()
# # board.reset_king_test()
# # board.set_turn()
# # print(board.make_move('d5', 'd6'))
# # board.print_board()
# # board.reset_king_test()
# # board.set_turn()
# # print(board.make_move('d5', 'c6'))
# # board.print_board()
# # board.reset_king_test()
# # board.set_turn()
# # print(board.make_move('d5', 'c5'))
# # board.print_board()
# # board.reset_king_test()
# # board.set_turn()
# # print(board.make_move('d5', 'c4'))
# # board.print_board()
# # board.reset_king_test()
# # board.set_turn()
# # print(board.make_move('d5', 'd4'))
# # board.print_board()
# # board.reset_king_test()
# # board.set_turn()
# # print(board.make_move('d5', 'e4'))
# # board.print_board()
# # board.reset_king_test()
# # board.set_turn()
# # print(board.make_move('d5', 'e5'))
# # board.print_board()
# # board.reset_king_test()
# # board.set_turn()
# # print(board.make_move('d5', 'f4'))  # False, cannot move like the knight
# # board.print_board()
# # board.reset_king_test()
# # board.set_turn()
# # print(board.make_move('d5', 'b3'))  # False, cannot move more than 1 square
# # board.print_board()
# # board.reset_king_test()
# # print(board.make_move('e2', 'e4'))
# # print(board.make_move('d5', 'e4'))
# # board.print_board()
# # print(board.make_move('d5', 'd4'))
# # print(board.make_move('e1', 'e2'))
# # print(board.make_move('d4', 'd3'))
# # board.print_board()
# # print(board.make_move('e2', 'd3'))
# # board.print_board()
# # print(board.get_game_state())
# # print(board.get_turn())
# # print(board.make_move('c2', 'd3'))
# # board.print_board()
# # print(board.get_game_state())
# # print(board.get_turn())
#
# # # [PASS] Submission Test #1 - Create game, test pawn moves, game state + turns
# #
# # [PASS] Submission Test #2 - Pawn Moves Without Capture
# print('SUB TEST 2 - Pawn Moves Without Capture')
# print('---------------------------------------')
# board.reset_game()
# print(board.make_move('a2', 'a4'))
# print(board.make_move('a7', 'a6'))
# print(board.make_move('a4', 'a5'))
# print(board.make_move('a6', 'a5'))
# print(board.make_move('a6', 'b5'))
# print(board.make_move('a6', 'a6'))
# print(board.make_move('a6', 'a7'))
# print(board.make_move('b7', 'b6'))
# #
# # [PASS] Submission Test #3 - Pawn Captures Pawn, No Other Pieces Affected By Explosion
# print('SUB TEST 3 - Pawn Captures Pawn, No Other Pieces Affected By Explosion')
# print('----------------------------------------------------------------------')
# board.reset_game()
# print(board.make_move('a2', 'a4'))
# print(board.make_move('a7', 'a6'))
# print(board.make_move('a4', 'a5'))
# print(board.make_move('b7', 'b6'))
# print(board.make_move('a5', 'b6'))
#
# # [PASS] Submission Test #4 - Pawn captures pawn with explosion removing proper pieces
# print('SUB TEST 4 - Pawn captures pawn with explosion removing proper pieces')
# print('---------------------------------------------------------------------')
# board.reset_game()
# print(board.make_move('a2', 'a4'))
# print(board.make_move('g7', 'g5'))
# print(board.make_move('a4', 'a5'))
# print(board.make_move('g5', 'g4'))
# print(board.make_move('a5', 'a6'))
# print(board.make_move('g4', 'g3'))
# print(board.make_move('a6', 'b7'))
# #
# # [PASS] Submission Test #5 - Pawn Capture Pawn and Kills King, Game End
# print('SUB TEST 5 - Pawn Capture Pawn and Kills King, Game End')
# print('-------------------------------------------------------')
# board.reset_game()
# print('[1] Game State:', board.get_game_state())
# print(board.make_move('a2', 'a4'))
# print(board.make_move('g7', 'g5'))
# print(board.make_move('a4', 'a5'))
# print(board.make_move('g5', 'g4'))
# print(board.make_move('a5', 'a6'))
# print('[2] Game State:', board.get_game_state())
# print(board.make_move('g4', 'g3'))
# print('[3] Game State:', board.get_game_state())
# print(board.make_move('a6', 'b7'))
# print('[4] Game State:', board.get_game_state())
# print(board.make_move('g3', 'f2'))
# print('[5] Game State:', board.get_game_state())
#
# # [PASS] My Test for Rook:
# print('MY TEST ROOK')
# print('------------')
# board.reset_game()
# print(board.make_move('a2', 'a4'))
# print(board.make_move('h7', 'h5'))
# print(board.make_move('a1', 'a3'))
# print(board.make_move('f7', 'f6'))
# print('PLayer turn:', board.get_turn())
# print(board.make_move('a3', 'e3'))
# print(board.make_move('f6', 'f5'))
# print(board.make_move('e3', 'e5'))
# print(board.make_move('f5', 'f4'))
# print(board.make_move('e5', 'c5'))
# print(board.make_move('g7', 'g5'))
# print(board.make_move('c5', 'c3'))
#
# # [PASS] Submission Test #6 - Rook + Pawn Movements with Rook Capture
# print('SUB TEST 6 - Rook + Pawn Movements with Rook Capture')
# print('----------------------------------------------------')
# board.reset_game()
# print(board.make_move('a2', 'a4'))
# print(board.make_move('h7', 'h5'))
# # White Move
# print(board.make_move('a1', 'a5'))
# print(board.make_move('a1', 'a3'))
# # Black Move
# print(board.make_move('h8', 'f6'))
# print(board.make_move('h8', 'g6'))
# print(board.make_move('h8', 'h9'))
#
# # [] Submission Test #7 - Knight Movement
# print('SUB TEST 7 - Knight Movement')
# print('----------------------------')
# board.reset_game()
# print(board.make_move('b1', 'c3'))
# print(board.make_move('g8', 'h6'))
# print(board.make_move('c3', 'a5'))
# #
# print('MY KNIGHT TEST')
# print('----------------------------')
# board.reset_game()
# print(board.make_move('b1', 'c3'))
# print(board.make_move('b8', 'a6'))
# print(board.make_move('c3', 'd6'))
# print(board.make_move('c3', 'a4'))
# print(board.make_move('a6', 'b4'))
# print(board.make_move('a4', 'c3'))
# print(board.make_move('b4', 'e5'))
# print(board.make_move('b4', 'a2'))
# print(board.make_move('c3', 'a2'))
#
# # [DONE] Submission Test #8 - Bishop Movement with Captures
# print('SUB TEST 8 - Bishop Movement with Captures')
# print('------------------------------------------')
# board.reset_game()
# print(board.make_move('d2', 'd4'))
# print(board.make_move('e7', 'e5'))
# print(board.make_move('c1', 'a3'))
# print(board.make_move('c1', 'h6'))  # RU
# print(board.make_move('f8', 'c5'))  # LD
# print(board.make_move('h6', 'g7'))  # LU
# print(board.make_move('c5', 'd4'))  # RD
#
#
# # [DONE] Submission Test #9 - Queen Movement with Captures + End of Game
# print('SUB TEST 9 - Queen Movement with Captures + End of Game')
# print('-------------------------------------------------------')
# board.reset_game()
# print(board.make_move('e2', 'e4'))
# print(board.make_move('d7', 'd5'))
# print(board.make_move('d1', 'd4'))
# print(board.make_move('d1', 'g4'))
# print(board.make_move('d8', 'f6'))
# print(board.make_move('d8', 'd6'))
# print(board.make_move('g4', 'c8'))
# print(board.make_move('d6', 'b4'))
# print(board.make_move('c8', 'c7'))
# print(board.make_move('f2', 'f3'))
# print(board.make_move('b4', 'd2'))
#
#
#
# # Need to try capturing another piece with a king
# # [PASS] Submission Test #10 - King Movement
# print('SUB TEST 10 - King Movement')
# print('---------------------------')
# board.reset_game()
# print(board.make_move('e2', 'e4'))
# print(board.make_move('e7', 'e5'))
# print(board.make_move('e1', 'e3'))
# print(board.make_move('e1', 'f1'))
# print(board.make_move('e1', 'e2'))
# print(board.make_move('e8', 'd7'))
# print(board.make_move('e8', 'e7'))
# print(board.make_move('e2', 'f3'))
# # End their test, start of my test for backwards motion + king not being able to capture other pieces
# print(board.make_move('c7', 'c6'))
# print(board.make_move('f3', 'e1'))
# board.print_board()
# print(board.make_move('f3', 'f4'))
# board.print_board()
# print(board.make_move('h7', 'h5'))
# print(board.make_move('f4', 'e5'))
# board.print_board()
# print(board.get_game_state())
